In [1]:
import numpy as np

x = np.random.randint(1, 100, 10)
print("Original array:", x)

y = np.sort(x)
print("After np.sort():", y)
print("Original unchanged:", x)

x.sort()
print("After x.sort():", x)

Original array: [64 69 33 37 23  9 77 14 98 16]
After np.sort(): [ 9 14 16 23 33 37 64 69 77 98]
Original unchanged: [64 69 33 37 23  9 77 14 98 16]
After x.sort(): [ 9 14 16 23 33 37 64 69 77 98]


In [2]:
import numpy as np

x = np.random.randint(1, 100, 10)
print("Original array:", x)

i = np.argsort(x)
print("Sorted indices:", i)

print("Using fancy indexing:", x[i])
print("Using np.sort():", np.sort(x))

print("Both are equal:", np.array_equal(x[i], np.sort(x)))

Original array: [42 23 83 31 80 83 28 80 23  4]
Sorted indices: [9 1 8 6 3 0 7 4 5 2]
Using fancy indexing: [ 4 23 23 28 31 42 80 80 83 83]
Using np.sort(): [ 4 23 23 28 31 42 80 80 83 83]
Both are equal: True


In [3]:
import numpy as np

x = np.random.randint(1, 100, (4, 6))
print("Original array:\n", x)

row_sorted = np.sort(x, axis=1)
print("\nRows sorted independently:\n", row_sorted)

col_sorted = np.sort(x, axis=0)
print("\nColumns sorted independently:\n", col_sorted)

Original array:
 [[83 68 10 59 78 60]
 [83 51 21 47 81 52]
 [19 64 51 61 98 72]
 [76 20 36 54 58 57]]

Rows sorted independently:
 [[10 59 60 68 78 83]
 [21 47 51 52 81 83]
 [19 51 61 64 72 98]
 [20 36 54 57 58 76]]

Columns sorted independently:
 [[19 20 10 47 58 52]
 [76 51 21 54 78 57]
 [83 64 36 59 81 60]
 [83 68 51 61 98 72]]


In [4]:
import numpy as np

x = np.random.randint(1, 100, 15)
print("Original array:", x)

p = np.partition(x, 4)
print("Partitioned array:", p)
print("Four smallest values:", p[:4])

print("Verified using np.sort():", np.sort(x)[:4])

Original array: [98 69 21 67  8 19  2 47 27 99 39 81 33 98 68]
Partitioned array: [ 2  8 19 21 27 33 39 47 67 68 69 81 98 98 99]
Four smallest values: [ 2  8 19 21]
Verified using np.sort(): [ 2  8 19 21]


In [5]:
import numpy as np

student_names = np.array([
    'Rahul', 'Priya', 'Amit', 'Sneha', 'Kiran'
])

scores = np.array([85, 92, 76, 95, 88])

i = np.argsort(scores)

print("Students ranked from lowest to highest:")
for j in i:
    print(student_names[j], scores[j])

Students ranked from lowest to highest:
Amit 76
Rahul 85
Kiran 88
Priya 92
Sneha 95


In [6]:
import numpy as np

X = np.random.rand(10, 2)
print("Points:\n", X)

dist_sq = np.sum(
    (X[:, np.newaxis, :] - X[np.newaxis, :, :]) ** 2,
    axis=-1
)

print("\nPairwise squared-distance matrix:\n", dist_sq)

i = np.argsort(dist_sq, axis=1)

# Exclude each point itself (distance = 0)
nearest = i[:, 1:3]

print("\nIndices of 2 nearest neighbors:")
for j in range(10):
    print("Point", j, "->", nearest[j])

Points:
 [[0.9039479  0.59434182]
 [0.1309847  0.10013175]
 [0.9088725  0.04400872]
 [0.3822738  0.73730698]
 [0.57388385 0.98964972]
 [0.08358199 0.32010464]
 [0.84394677 0.81087792]
 [0.91988741 0.51113997]
 [0.40911116 0.06982095]
 [0.7325552  0.58653173]]

Pairwise squared-distance matrix:
 [[0.         0.8417157  0.30289077 0.29258291 0.26521061 0.74820626
  0.05048802 0.00717661 0.51998555 0.02943645]
 [0.8417157  0.         0.60825923 0.46913849 0.98740188 0.05063509
  1.01347504 0.79129525 0.07827307 0.59847201]
 [0.30289077 0.60825923 0.         0.75796868 1.0064543  0.75733339
  0.59230371 0.21833294 0.25042768 0.32541901]
 [0.29258291 0.46913849 0.75796868 0.         0.10039127 0.26327459
  0.21855462 0.34017991 0.44625785 0.14543024]
 [0.26521061 0.98740188 1.0064543  0.10039127 0.         0.68868653
  0.10489334 0.34869004 0.87323501 0.18768071]
 [0.74820626 0.05063509 0.75733339 0.26327459 0.68868653 0.
  0.81901302 0.73590126 0.16861117 0.49214963]
 [0.05048802 1.0134750